### ISSUE TITLE
PPRESS-257 ⁃ Notifications X days before/after publication date

### ISSUE THREAD

**Issue by jphorn** [OSTraining/PublishPress#12]
This is a modified copy/paste from an email conversation with Steve and explains our use case and feature request.

- - -
>>> [JPH] This is a pre-sale question: for our long-tail content we're looking for an option to remind us X days/weeks/months _after_ publication to check whether the article's content needs to be updated. On the actual reminder date this article needs to pop up on the editorial calendar again and notify (via Slack) the responsible team.
>>> I tried to replicate this with a custom status and/or a custom metadata, but both fall short. The metadata (type: Date) doesn't reposition the article on the calendar; it's only visible on the actual Publish date. Custom status doesn't work, since there's no status with future date possible _after_ Published.

>> [PS] The next step will be to add more notification options: for example "days after publication" or "days before scheduled publication". Would that work for you?

> [JPH] Yeah, that’ll work for now :-) You know how people treat notifications; register and move on ;-) So that’s why I trust them more with the Editorial Calendar route. Fortunately Slack has a reminder option, so that’s at least something. Editors are typically juggling 100 things at a time, so gently nagging them is the most important part. I don’t mind them deferring, but eventually their follow-up task needs to be completed. 
> Our use case: we’re an Apple enthusiast community (like Macrumors, but Dutch). We have several (buying) guides, howtos and other content types which need frequent updating after Apple releases new firmware versions and/or new products. So some articles need to be refreshed every month, others every quarter. We have tried to use Asana and other project tools, but due to the lack of WordPress integration they all fail since there’s too many steps. I’m betting PublishPress is able to fill that void, but the notify/remind system is very important to us.

**Comment by stevejburge** [comment]
Wonderful idea, thanks @jphorn. It's great to hear about these use-cases we hadn't considered.

We had been thinking about expanding the Notifications in this way ... "send a reminder X days before the scheduled publishing date"

So if someone is assigned as an author, they can get an email to remind them ... “Pay attention! Your post is scheduled to publish in 5 days!”

That could easily be expanded to meet your use-case ... "send a reminder X days after the publishing date".

So if someone is assigned as an author, they can get an email to remind them ... "Your post was published 30 days ago. Check to see it’s still accurate”

**Comment by jphorn** [comment]
Thanks for looking into this @stevejburge. In my original question I asked:
> On the actual reminder date this article needs to pop up on the editorial calendar again and notify (via Slack) the responsible team.
> I tried to replicate this with a custom status and/or a custom metadata, but both fall short. The metadata (type: Date) doesn't reposition the article on the calendar; it's only visible on the actual Publish date. Custom status doesn't work, since there's no status with future date possible after Published.

While adding this issue I thought: wouldn't it be easier to also add (future) **notifications** to the Editorial Calendar instead of the _actual post for which the reminder_ is. I'd still rather have the post, but since there's no future date after published_date there's nothing to work with for you as far as displaying on the calendar goes.
So the issue's title reflects this thought. You could treat the notifications on the Editorial Calendar the same as you have posts now; with a fly-out menu where the linked post is visible.

I hope that makes sense :-)

![screen-shot-2017-09-21-15-59-40](https://user-images.githubusercontent.com/478156/30699981-86166b48-9ee6-11e7-9859-a35a37135d49.png)
_this could be a notification for the linked post, instead of the post itself (which is already on the Calendar on its publish date)_

**Comment by stevejburge** [comment]
Thanks @jphorn. That would require a slightly more complex solution, although I can see the benefits of having the notifications on the calendar.

Am I right in thinking that your future update dates are custom for each post? There's no clear pattern for which guides need updating every month and which need updating every quarter?
 
If that's true, we might need to rely on metadata to trigger the notifications.

**Comment by jphorn** [comment]
> Am I right in thinking that your future update dates are custom for each post? There's no clear pattern for which guides need updating every month and which need updating every quarter?

Correct. E.g. our 'hub page' for iPhone X currently needs refreshing once a week, whereas our 'hub page' for 'Overview of all major iOS versions' only needs to be refreshed once a year. And our buyers guide for any iPad once every month (for updated prices). I have a very long (outdated) list in Asana with all custom recurring schemes :-(

I think the logic is already present in your current metadata implementation. E.g. I made a custom metadata in your sandbox ('Refresh') with type: date. This metadata could be displayed on the Calendar the same way as you treat Posts. 
It's hard to explain in text, but you're actually reversing how you display Posts on the Calendar. Instead of displaying the post **itself** you're putting _an alias_ to the post on a later date (disguised as notification, with the datetime of the reminder).

**Comment by stevejburge** [comment]
Thanks. This is super-helpful

The notification part will definitely come first here. I'll talk with our developers to see how they would approach metadata into something that can be displayed on the calendar.

To make this clearer, let's leave this topic for the calendar. I've created a new issue for the notifications: https://github.com/OSTraining/PublishPress/issues/80

**Comment by OSTraining** [comment]
➤ Anderson Grüdtner Martins commented:

https://secure.helpscout.net/conversation/435708104/57094/?folderId=898239

**Comment by stevejburge** [comment]
Mostly solved with the reminders add-on
