### ISSUE TITLE
PPRESS-347 ⁃ Conflict with User Access Manager

### ISSUE THREAD

**Issue by OSTraining** [OSTraining/PublishPress#157]
Error 500.

#### Support ticket (private)
https://secure.helpscout.net/conversation/527718735/64265?folderId=898239

**Comment by OSTraining** [comment]
➤ Anderson Grüdtner Martins commented:

It seems to be related to the permissions add-on.

**Comment by OSTraining** [comment]
➤ Anderson Grüdtner Martins commented:

The error seems to be related to memory usage. It gets out of memory, because the filter user_has_cap is applied by the UAM too many times. That makes our plugin runs like a crazy.

**Comment by stevejburge** [comment]
Solved in new release of Permissions
