### ISSUE TITLE
PPRESS-350 ⁃ Editors can't see the calendar. Only works for Authors

### ISSUE THREAD

**Issue by OSTraining** [OSTraining/PublishPress#159]
#### Support ticket (private)
https://secure.helpscout.net/conversation/532153526/64658?folderId=898239
https://secure.helpscout.net/conversation/525256071/64066?folderId=898239

**Comment by OSTraining** [comment]
➤ Anderson Grüdtner Martins commented:

Send beta for users...

**Comment by stevejburge** [comment]
Solved in new version of Permissions
