### ISSUE TITLE
PPRESS-351 ⁃ Refine autoload behavior to prevent fatal if local `vendor` isn't used

### ISSUE THREAD

**Issue by davisshaver** [OSTraining/PublishPress#160]
If a developer is using Composer to manage dependencies, the local `vendor` folder will not be populated, but we can assume that the autoload is helping elsewhere.

**Comment by davisshaver** [comment]
It looks like the feature plugins will need this tweaked too. I am going to create PR's against them now.

**Comment by andergmartins** [comment]
Thanks, we appreciate the help @davisshaver. Please, just make sure to send pull requests to the "development" branches. I'm going to release them today.
