### ISSUE TITLE
PPRESS-249 ⁃ Allow to import users/user groups using CSV file/text

### ISSUE THREAD

**Issue by OSTraining** [OSTraining/PublishPress#72]
Add form to upload a CSV file or paste the text. Allowing to import user groups and users, or add a relationship between users and user groups, for large sites.

**Request:**
https://secure.helpscout.net/conversation/429989575/56635/?folderId=898239

**Comment by stevejburge** [comment]
Not sure this is within the scope of PublishPress. Other plugins do it well
